version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb-data:/data/db
  database-service:
    container_name: database-service
    build: ./database-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - mongodb
  backend-service:
    container_name: backend-service
    build: ./backend-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_SERVICE_URL:http://databaseservice:8081
    depends_on:
      - mongodb
      - database-service
  ui-service:
    container_name: ui-service
    build: ./ui-service
    ports:
            - "3000:80"
    depends_on:
      - mongodb
      - database-service