# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dev
# ---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  selector:
    app: ui-service
  ports:
    - port: 3000
      targetPort: 80
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  selector:
    matchLabels:
      app: ui-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui-service
        tier: ui-service
    spec:
      serviceAccountName: default
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - image: 774305578623.dkr.ecr.sa-east-1.amazonaws.com/ui-service:latest
          name: ui-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: ui-service